Numpy (Array Processing)

1. Create a NumPy array with 10 random integers between 0 and 100.

In [3]:
import numpy as np

In [4]:
arr = np.random.randint(0,100,10)
arr

array([28, 69, 12, 28, 22,  1, 96, 67, 28, 54])

2. Use the np.where() function to create a new array with the same shape as the previous one, where values less than 50 are replaced with -1 and values greater than or equal to 50 are replaced with 1.

In [29]:
arr = np.random.randint(0,100,10)
print('arr values: ', arr)
print('numpy.where:', np.where(50<=arr, 1, -1))

arr values:  [50 54 19 25 86 39 90 72 23 66]
numpy.where: [ 1  1 -1 -1  1 -1  1  1 -1  1]


3. Calculate the mean, median, and standard deviation of the original array.

In [54]:
arr = np.random.randint(0,100,10)
print('Mean   :', np.mean(arr))
print('Median :', np.median(arr))
print('Standard Deviation:', np.std(arr))

Mean   : 45.7
Median : 36.0
Standard Deviation: 25.550146770615626


4. Create a boolean array that is True where the values in the original array are even, and False otherwise.

In [67]:
arr = np.random.randint(0,100,10)
print('Array :\n', arr)
print('Boolean array:\n',arr%2 == 0)


Array :
 [18 10 43 13 82 16 35 69 15 35]
Boolean array:
 [ True  True False False  True  True False False False False]


5. Sort the original array in ascending order.

In [69]:
arr = np.random.randint(0,100,10)
print(np.sort(arr))

[14 28 35 38 38 43 49 52 54 63]


6. Find the unique values in the original array.


In [74]:
arr = np.random.randint(0,100,10)
print('Original array:', arr)
print(np.unique(arr))

Original array: [90  4 15 86 35 12 32 90 93 52]
[ 4 12 15 32 35 52 86 90 93]


7. Use the np.in1d() function to create a boolean array indicating which elements of the original array are also present in a new array with 5 random integers between 0 and 100.


In [82]:
arr = np.random.randint(0,100,10)
print('Original array:', arr)
arr2 = np.random.randint(0,100,5)
print('New array     :', arr2)

np.in1d(arr,arr2)


Original array: [ 0 49 55 90 68 68 74  0 39 80]
New array     : [24  0  6 45 21]


array([ True, False, False, False, False, False, False,  True, False,
       False])

8. Save the original array to a text file named "my_array.txt" using the np.savetxt() function.

In [88]:
arr = np.random.randint(0,100,10)
print('Original array:', arr)
np.savetxt('my_array.txt', arr)

Original array: [18 52 15]
