In [1]:
import numpy as np

####### 1. Create a 1D NumPy array with the integers from 0 to 9. Extract the 3rd element from the array.

In [11]:
a = np.arange(0,10)
print(a)

[0 1 2 3 4 5 6 7 8 9]


In [16]:
a[2]

2

####### 2. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Extract the element at row 2, column 1.

In [21]:
array = np.random.rand(3,3)
array

array([[0.02150136, 0.42811352, 0.03738926],
       [0.04346959, 0.11076853, 0.77366716],
       [0.05960207, 0.91120573, 0.88744871]])

In [22]:
array[2][1]

0.911205730749302

3. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Extract the subarray consisting of the first 2 rows and the last 2 columns.

In [30]:
array = np.random.rand(4,4)
array


array([[0.8448455 , 0.3474935 , 0.98967176, 0.70462181],
       [0.63966199, 0.43664188, 0.34869763, 0.93323806],
       [0.84905871, 0.04521329, 0.55391123, 0.25440539],
       [0.87334745, 0.51369992, 0.91290829, 0.76121398]])

In [41]:
array[:2, 2:]

array([[0.98967176, 0.70462181],
       [0.34869763, 0.93323806]])

4. Create a 1D NumPy array with the integers from 0 to 9. Copy a slice of the array consisting of the first 3 elements.

In [45]:
a = np.arange(0,10)
a2 = a[:3].copy()
a2

array([0, 1, 2])

5. Create a 2D NumPy array with shape (3, 3) and fill it with random numbers. Copy a slice of the array consisting of the first 2 rows and the first 2 columns.

In [46]:
array = np.random.rand(3,3)
array


array([[0.92030929, 0.33473853, 0.80323653],
       [0.11944753, 0.65737104, 0.60115182],
       [0.91318304, 0.84257827, 0.0270013 ]])

In [48]:
array2 = array[:2, :2]
array2

array([[0.92030929, 0.33473853],
       [0.11944753, 0.65737104]])

6. Create a 1D NumPy array with the integers from 0 to 9. Reshape the array into a 2D array with shape (3, 3).

In [51]:
a = np.arange(0,9)
arr = a.reshape(3,3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

7. Create a 2D NumPy array with shape (4, 4) and fill it with random numbers. Reshape the array into a 1D array.

In [52]:
arr = np.random.rand(4,4)
arr

array([[0.6993676 , 0.11784818, 0.67248502, 0.08498394],
       [0.97025583, 0.88084527, 0.60091079, 0.36427899],
       [0.35675616, 0.59590292, 0.78028985, 0.9271515 ],
       [0.51202005, 0.64230439, 0.71805844, 0.93774269]])

In [56]:
resh = arr.reshape(-1)
resh

array([0.6993676 , 0.11784818, 0.67248502, 0.08498394, 0.97025583,
       0.88084527, 0.60091079, 0.36427899, 0.35675616, 0.59590292,
       0.78028985, 0.9271515 , 0.51202005, 0.64230439, 0.71805844,
       0.93774269])

8. Create two 1D NumPy arrays with the integers from 0 to 4. Concatenate the two arrays into a single 1D array.

In [57]:
a1 = np.arange(0,4)
a2 = np.arange(0,4)
a = a1+a2
a

array([0, 2, 4, 6])