In [1]:
import numpy as np

In [2]:
l1 = [1,2,3,4]
arr1 = np.array(l1)
print(arr1)

[1 2 3 4]


In [3]:
l2 = [11,22,33,44]

In [6]:
l = [l1, l2]
print(l)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [5]:
arr_2D = np.array(l)
print(l)

[[1, 2, 3, 4], [11, 22, 33, 44]]


In [7]:
arr_2D.shape

(2, 4)

In [8]:
arr_2D.dtype

dtype('int32')

In [12]:
np.zeros(3,'int')

array([0, 0, 0, 0, 0])

In [11]:
np.ones(3)

array([1., 1., 1.])

In [13]:
np.ones([3,3])

array([[1., 1., 1.],
       [1., 1., 1.],
       [1., 1., 1.]])

In [14]:
np.zeros(3)
np.empty(3) 

array([0., 0., 0.])

In [15]:
np.eye(4)

array([[1., 0., 0., 0.],
       [0., 1., 0., 0.],
       [0., 0., 1., 0.],
       [0., 0., 0., 1.]])

In [16]:
np.arange(10)

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [17]:
np.arange(0,50,2)

array([ 0,  2,  4,  6,  8, 10, 12, 14, 16, 18, 20, 22, 24, 26, 28, 30, 32,
       34, 36, 38, 40, 42, 44, 46, 48])