####### Create 2*2 NumPy array and multiply it by 2 

In [1]:
import numpy as np

In [7]:
li1 = [1,2]
li2 = [4,5]
li = [li1,li2]
ar = np.array(li)
print(ar*2)

[[ 2  4]
 [ 8 10]]


####### Create 3*3 Numpy array and add 5 to each element.

In [8]:
li1 = [1,2,3]
li2 = [4,5,7]
li3 = [8,9,10]
li = [li1,li2,li3]
ar = np.array(li)
print(ar+5)

[[ 6  7  8]
 [ 9 10 12]
 [13 14 15]]


####### Create 4*4 Numpy array and subtract 10 from each element.

In [9]:
li1 = [1,2,3,12]
li2 = [4,5,7,45]
li3 = [8,9,10,89]
li4 = [11,12,13,111]
li = [li1,li2,li3,li4]
ar = np.array(li)
print(ar-10)

[[ -9  -8  -7   2]
 [ -6  -5  -3  35]
 [ -2  -1   0  79]
 [  1   2   3 101]]


####### Create 5*5 Numpy array and divide each element by 2.

In [12]:
ar = np.array([[1,2,3,12,31], [4,5,7,45,74], [8,9,10,89,108],[11,12,13,111,213], [14,15,16,141,516]])
print(ar/2)

[[  0.5   1.    1.5   6.   15.5]
 [  2.    2.5   3.5  22.5  37. ]
 [  4.    4.5   5.   44.5  54. ]
 [  5.5   6.    6.5  55.5 106.5]
 [  7.    7.5   8.   70.5 258. ]]


####### Create 6*6 Numpy array and calculate the square root of each element.

In [15]:
ar = np.array([[1,2,3,12,31,23], [4,5,7,45,74,57], [8,9,10,89,108,91],
               [11,12,13,111,213,121], [14,15,16,141,516,614], [17,18,19,71,81,97]])
print(ar**0.5)

[[ 1.          1.41421356  1.73205081  3.46410162  5.56776436  4.79583152]
 [ 2.          2.23606798  2.64575131  6.70820393  8.60232527  7.54983444]
 [ 2.82842712  3.          3.16227766  9.43398113 10.39230485  9.53939201]
 [ 3.31662479  3.46410162  3.60555128 10.53565375 14.59451952 11.        ]
 [ 3.74165739  3.87298335  4.         11.87434209 22.71563338 24.77902339]
 [ 4.12310563  4.24264069  4.35889894  8.42614977  9.          9.8488578 ]]
