Numpy (Universal Array Function)

In [9]:
import numpy as np

2. Create a NumPy array with shape (4,4) and fill it with random numbers. Use the np.sin() function to compute the sine of each element in the array.

In [10]:
ar = np.random.rand(4,4)
print("Before:", ar)
s = np.sin(ar)
print('After:', s)

Before: [[0.68864424 0.53729573 0.98467271 0.32520877]
 [0.49285925 0.70848915 0.79649641 0.40092599]
 [0.06525904 0.35163824 0.50501403 0.54429136]
 [0.84441608 0.10395887 0.96648981 0.68037511]]
After: [[0.63549097 0.51181464 0.8330911  0.31950662]
 [0.47314678 0.65068726 0.71491072 0.39027106]
 [0.06521273 0.34443627 0.48381972 0.51781198]
 [0.74758342 0.10377171 0.82289633 0.62908466]]


3. Create a NumPy array with shape (5,5) and fill it with random numbers. Use the np.log() function to compute the natural logarithm of each element in the array.

In [11]:
ar = np.random.rand(5,5)
print("Before:", ar)
s = np.log(ar)
print('After:', s)

Before: [[0.58925522 0.24801212 0.61326036 0.67903658 0.00801514]
 [0.3018749  0.40310493 0.90801726 0.96874649 0.61659945]
 [0.07823674 0.32457912 0.65207919 0.93826829 0.55262838]
 [0.68231392 0.63192641 0.0506093  0.26599027 0.29750558]
 [0.77559216 0.41783565 0.648515   0.03925492 0.1361188 ]]
After: [[-0.52889588 -1.39427764 -0.4889657  -0.38708028 -4.82642304]
 [-1.19774258 -0.90855839 -0.09649189 -0.03175232 -0.48353565]
 [-2.5480159  -1.12522596 -0.42758926 -0.06371934 -0.59306951]
 [-0.38226543 -0.45898232 -2.98361991 -1.32429554 -1.21232231]
 [-0.25412847 -0.87266711 -0.43307014 -3.2376786  -1.99422721]]


4. Create a NumPy array with shape (2,2) and fill it with random numbers. Use the np.sqrt() function to compute the square root of each element in the array.

In [14]:
ar = np.random.rand(2,2)
print("Before:", ar)
s = np.sqrt(ar)
print('After:', s)

Before: [[0.14298496 0.1647797 ]
 [0.66209632 0.99966843]]
After: [[0.37813352 0.40593066]
 [0.81369301 0.9998342 ]]


8. Create a NumPy array with 5 random integers between 1 and 10. Use the maximum function to find the largest element in the array.

In [18]:
ar = np.random.randint(1,11,5)
print('Random numbers', ar)
print('Maximum :', np.max(ar))

Random numbers [2 6 3 4 2]
Maximum : 6


9. Create a NumPy array with 10 random floating-point numbers between 0 and 1. Use the round function to round each element to the nearest integer.

In [25]:
ar = np.random.normal(0,1,10)
print('Random numbers', ar)
print('Nearest intergers :', np.round(ar))

Random numbers [ 0.90336728  0.75793563 -0.29948     0.2913276   0.61454299  0.46022435
 -0.0438216  -0.04204033  1.34278737  0.84867902]
Nearest intergers : [ 1.  1. -0.  0.  1.  0. -0. -0.  1.  1.]


10. Create a NumPy array with 7 random integers between 1 and 100. Use the argmax function to find the index of the largest element in the array.

In [27]:
ar = np.random.randint(1,100,7)
print('Random numbers', ar)
print('The index of the maximum number :', np.argmax(ar))

Random numbers [24 35 78 15  2 11 55]
The index of the maximum number : 2


11. Create two NumPy arrays with the same shape, each filled with random integers between 1 and 10. Use the add function to add the two arrays together element-wise.

In [30]:
ar1 = np.random.randint(1,10)
ar2 = np.random.randint(1,10)
print('Random number 1:', ar1)
print('Random number 2:', ar2)
print('The addition of the two numbers :', np.add(ar1, ar2))

Random number 1: 2
Random number 2: 4
The addition of the two numbers : 6


12. Create a NumPy array with 12 random integers between 0 and 100. Use the clip function to limit the values in the array to a range between 10 and 90.

In [39]:
ar = np.random.randint(0,100,12)

print(ar.clip(10,90))

[50 15 49 60 34 27 67 35 17 49 45 70]
